data2 <- read.table('ATspinodal.txt',header=T)
data2 <- read.table('./src/data/ATspinodal.txt',header=T)
getwd()
data2 <- read.table('../src/data/ATspinodal.txt',header=T)
ls()
data2 <- read.table('../src/data/ATspinodal.txt',header=T)
data2 <- read.table('../src/data/PTspinodal.txt',header=T)
ls()
rm(ls())
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
data <- read.table('../src/Data/PTspinodal.txt',header=T)
attach(data)
lmA1=lm(pressure~poly(reduced_temperature,1))
lmA2=lm(pressure~poly(reduced_temperature,2))
lmA3=lm(pressure~poly(reduced_temperature,3))
lmA4=lm(pressure~poly(reduced_temperature,4))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA3,lmA4)
plot(reduced_temperature,pressure)
lines(reduced_temperature,fitted(lmA3))
data <- read.table('../src/Data/PTspinodal.txt',header=T)
attach(data)
lmA1=lm(pressure~poly(reduced_temperature,1))
lmA2=lm(pressure~poly(reduced_temperature,2))
lmA3=lm(pressure~poly(reduced_temperature,3))
lmA4=lm(pressure~poly(reduced_temperature,4))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA3,lmA4)
plot(reduced_temperature,pressure)
lines(reduced_temperature,fitted(lmA3))
rm(list=ls())
data <- read.table('../src/Data/PTspinodal.txt',header=T)
attach(data)
lmA1=lm(pressure~poly(reduced_temperature,1))
lmA2=lm(pressure~poly(reduced_temperature,2))
lmA3=lm(pressure~poly(reduced_temperature,3))
lmA4=lm(pressure~poly(reduced_temperature,4))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA3,lmA4)
plot(reduced_temperature,pressure)
lines(reduced_temperature,fitted(lmA3))
rm(list=ls())
data <- read.table('../src/Data/PTspinodal.txt',header=T)
attach(data)
lmA1=lm(pressure~poly(reduced_temperature,1))
lmA2=lm(pressure~poly(reduced_temperature,2))
lmA3=lm(pressure~poly(reduced_temperature,3))
lmA4=lm(pressure~poly(reduced_temperature,4))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA3,lmA4)
plot(reduced_temperature,pressure)
lines(reduced_temperature,fitted(lmA3))
rm(list=ls())
data <- read.table('../src/Data/PTspinodal.txt',header=T)
attach(data)
lmA1=lm(pressure~poly(reduced_temperature,1))
lmA2=lm(pressure~poly(reduced_temperature,2))
lmA3=lm(pressure~poly(reduced_temperature,3))
lmA4=lm(pressure~poly(reduced_temperature,4))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA3,lmA4)
plot(reduced_temperature,pressure)
lines(reduced_temperature,fitted(lmA3))
rm(list=ls())
data <- read.table('../src/Data/PTspinodal.txt',header=T)
attach(data)
lmA1=lm(pressure~poly(reduced_temperature,1))
lmA2=lm(pressure~poly(reduced_temperature,2))
lmA3=lm(pressure~poly(reduced_temperature,3))
lmA4=lm(pressure~poly(reduced_temperature,4))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA3,lmA4)
plot(reduced_temperature,pressure)
lines(reduced_temperature,fitted(lmA3))
rm(list=ls())
data <- read.table('../src/Data/PTspinodal.txt',header=T)
attach(data)
lmA1=lm(pressure~poly(reduced_temperature,1))
lmA2=lm(pressure~poly(reduced_temperature,2))
lmA3=lm(pressure~poly(reduced_temperature,3))
lmA4=lm(pressure~poly(reduced_temperature,4))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA3,lmA4)
plot(reduced_temperature,pressure)
lines(reduced_temperature,fitted(lmA3))
rm(list=ls())
data <- read.table('../src/Data/PTspinodal.txt',header=T)
attach(data)
lmA1=lm(pressure~poly(reduced_temperature,1))
lmA2=lm(pressure~poly(reduced_temperature,2))
lmA3=lm(pressure~poly(reduced_temperature,3))
lmA4=lm(pressure~poly(reduced_temperature,4))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA3,lmA4)
plot(reduced_temperature,pressure)
lines(reduced_temperature,fitted(lmA3))
rm(list=ls())
data <- read.table('../src/Data/ATspinodal.txt',header=T)
attach(data)
lmA1=lm(Afactor~poly(reduced_temperature,1))
lmA2=lm(Afactor~poly(reduced_temperature,2))
lmA3=lm(Afactor~poly(reduced_temperature,3))
lmA4=lm(Afactor~poly(reduced_temperature,4))
lmA5=lm(Afactor~poly(reduced_temperature,5))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA2,lmA4)
anova(lmA3,lmA4)
anova(lmA4,lmA5)
plot(reduced_temperature,Afactor)
lines(reduced_temperature,fitted(lmA4))
rm(list=ls())
data <- read.table('../src/Data/ATspinodal.txt',header=T)
attach(data)
lmA1=lm(Afactor~poly(reduced_temperature,1))
lmA2=lm(Afactor~poly(reduced_temperature,2))
lmA3=lm(Afactor~poly(reduced_temperature,3))
lmA4=lm(Afactor~poly(reduced_temperature,4))
lmA5=lm(Afactor~poly(reduced_temperature,5))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA2,lmA4)
anova(lmA3,lmA4)
anova(lmA4,lmA5)
plot(reduced_temperature,Afactor)
lines(reduced_temperature,fitted(lmA2))
lmA2
lmA4
lmA1
rm(list=ls())
data <- read.table('../src/Data/ATspinodal.txt',header=T)
attach(data)
lmA1=lm(Afactor~poly(reduced_temperature,1))
lmA2=lm(Afactor~poly(reduced_temperature,2))
lmA3=lm(Afactor~poly(reduced_temperature,3))
lmA4=lm(Afactor~poly(reduced_temperature,4))
lmA5=lm(Afactor~poly(reduced_temperature,5))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA2,lmA4)
anova(lmA3,lmA4)
anova(lmA4,lmA5)
plot(reduced_temperature,Afactor)
lines(reduced_temperature,fitted(lmA2))
class(data)
dim(data)
data <- data[1:20,]
dim(data)
rm(list=ls())
data <- read.table('../src/Data/ATspinodal.txt',header=T)
data <- data[1:20,]
class(data)
attach(data)
lmA1=lm(Afactor~poly(reduced_temperature,1))
lmA2=lm(Afactor~poly(reduced_temperature,2))
lmA3=lm(Afactor~poly(reduced_temperature,3))
lmA4=lm(Afactor~poly(reduced_temperature,4))
lmA5=lm(Afactor~poly(reduced_temperature,5))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA2,lmA4)
anova(lmA3,lmA4)
anova(lmA4,lmA5)
plot(reduced_temperature,Afactor)
lines(reduced_temperature,fitted(lmA2))
rm(list=ls())
data <- read.table('../src/Data/ATspinodal.txt',header=T)
data <- data[2:21,]
class(data)
attach(data)
lmA1=lm(Afactor~poly(reduced_temperature,1))
lmA2=lm(Afactor~poly(reduced_temperature,2))
lmA3=lm(Afactor~poly(reduced_temperature,3))
lmA4=lm(Afactor~poly(reduced_temperature,4))
lmA5=lm(Afactor~poly(reduced_temperature,5))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA2,lmA4)
anova(lmA3,lmA4)
anova(lmA4,lmA5)
plot(reduced_temperature,Afactor)
lines(reduced_temperature,fitted(lmA2))
rm(list=ls())
data <- read.table('../src/Data/PTspinodal.txt',header=T)
attach(data)
lmA1=lm(pressure~poly(reduced_temperature,1))
lmA2=lm(pressure~poly(reduced_temperature,2))
lmA3=lm(pressure~poly(reduced_temperature,3))
lmA4=lm(pressure~poly(reduced_temperature,4))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA3,lmA4)
plot(reduced_temperature,pressure)
lines(reduced_temperature,fitted(lmA3))
rm(list=ls())
data <- read.table('../src/Data/ATspinodal.txt',header=T)
data <- data[2:21,]
class(data)
attach(data)
lmA1=lm(Afactor~poly(reduced_temperature,1))
lmA2=lm(Afactor~poly(reduced_temperature,2))
lmA3=lm(Afactor~poly(reduced_temperature,3))
lmA4=lm(Afactor~poly(reduced_temperature,4))
lmA5=lm(Afactor~poly(reduced_temperature,5))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA2,lmA4)
anova(lmA3,lmA4)
anova(lmA4,lmA5)
plot(reduced_temperature,Afactor)
lines(reduced_temperature,fitted(lmA2))
rm(list=ls())
data <- read.table('../src/Data/PTspinodal.txt',header=T)
attach(data)
lmA1=lm(pressure~poly(reduced_temperature,1))
lmA2=lm(pressure~poly(reduced_temperature,2))
lmA3=lm(pressure~poly(reduced_temperature,3))
lmA4=lm(pressure~poly(reduced_temperature,4))
anova(lmA1,lmA2)
anova(lmA2,lmA3)
anova(lmA3,lmA4)
plot(reduced_temperature,pressure)
lines(reduced_temperature,fitted(lmA3))
install.packages('FactoMineR')
library(FactoMineR)
data(geomorphology)
geomorphology
class(geomorphology)
summary(geomorphology)
library(tidyverse)
tibble_g <- as_tibble(geomorphology)
tibble_g
res <- FAMD(geomorphology)
summary(res)
summary(res)
res <- FAMD(geomorphology)
tibble_g
ls()
data2 <- read.table("../src/ScalingWaterModels/Features.dat",header=T)
as_tibble(data2)
FAMD(data2)
$eig
res2<-FAMD(data2)
res2
res2<-FAMD(data2)
class(data2)
distinct(data2$Property)
colnames(data2)
distinct(data2$Feature)
distinct(data2,Feature)
data3<- filter(data2,Feature=="Spinodal")
distinct(data3,Feature)
res2<-FAMD(data3)
data3<- filter(data2,Feature=="Widom")
res2<-FAMD(data3)
res2<-FAMD(data3)
res2.eig
res2$eig
data3<- filter(data2,Feature=="Spinodal")
res2<-FAMD(data3)
res2$eig

res2$eig
data3<- filter(data2,Feature=="Cpmax")
res2<-FAMD(data3)
res2$eig
res2<-FAMD(data3)
res2<-FAMD(data3)
distinct(data3,Feature)
distinct(data2,Feature)
data3<- filter(data2,Feature=="LLT")
res2<-FAMD(data3)
res2$eig
data3<- filter(data2,Feature=="Tmax")
res2<-FAMD(data3,graph=F)
res2$eig
data3<- filter(data2,Feature=="Ktmax")
res2<-FAMD(data3,graph=F)
res2$eig
data3<- filter(data2,Feature=="Ktmin")
res2<-FAMD(data3,graph=F)
res2$eig
distinct(data2,Feature)
data3<- filter(data2,Feature=="Widom")
res2<-FAMD(data3,graph=F)
res2$eig
data3<- filter(data2,Feature=="Widom",Feature=="Ktmax")
res2<-FAMD(data3,graph=F)
data3
data3<- filter(data2,Feature=="Widom" || Feature=="Ktmax")
data3
data3<- filter(data2,Feature=="Widom")
data3
data3<- filter(data2,Feature=="Widom" | Feature=="Ktmax")
data3
res2<-FAMD(data3,graph=F)
res2$eig
res2<-FAMD(data3,graph=T)
distinct(data3,Feature)
data3<- filter(data2,Feature=="Widom" | Feature=="Spinodal")
res2<-FAMD(data3,graph=F)
res2$eig
data3<- filter(data2,Feature=="Ktmax" | Feature=="Spinodal")
res2<-FAMD(data3,graph=F)
res2$eig
data3<- filter(data2,Feature=="Widom" | Feature=="Ktmax")
res2<-FAMD(data3,graph=F)
res2$eig
res2<-FAMD(data3,graph=T)
res2<-FAMD(data3,graph=T)
res2<-FAMD(data3,graph=T)
data3<- filter(data2,Feature=="Widom")
res2<-FAMD(data3,graph=T)
data3<- filter(data2,Feature=="Ktmax")
res2<-FAMD(data3,graph=T)
data3<- filter(data2,Feature=="Spinodal")
res2<-FAMD(data3,graph=T)
res2<-FAMD(data2)
exit()
q()
library(FactoMineR)
library(tidyverse)
data2W <- read.table("../src/ScalingWaterModels/FeaturesST2Widom.dat",header=T)
res2W<-FAMD(data2W,graph=F)
res2W
plot(res2W)
data2Wt <- data2W %>% as_tibble()
data2Wt
data2Wtt <- data2Wt[c(1,2,3)]
res2W<-FAMD(data2Wtt,graph=F)
plot(res2W)
data2Wtt <- data2Wt[c(1,2)]
res2W<-FAMD(data2Wtt,graph=F)
plot(res2W)
res2W<-PCA(data2Wtt,graph=F)
plot(res2W)
res2W
data2Wtt
plot(res2W)
data2T <- read.table("../src/ScalingWaterModels/Features.dat",header=T)
data2Tt <- data2T[c(1,2)]
res2T<-PCA(data2Tt,graph=F)
plot(res2T)
colnames(data2T)
data2TT -> data2T %>% filter(Source == "TSEOS")
data2TT <- data2T %>% filter(Source == "TSEOS")
data2Tt <- data2TT[c(1,2)]
res2T<-PCA(data2Tt,graph=F)
plot(res2T)
res2T<-PCA(data2Tt,graph=F)
plot(res2T)
data2Tt
ls()
dataW2tt
head(data2Wt)
ls()
head(data2Wtt)
head(data2Ttt)
head(data2Tt)
rbind(data2Ttt,data2Wtt)
rbind(data2Tt,data2Wtt)
dataAt<-rbind(data2Tt,data2Wtt)
resAT<-PCA(data2At,graph=F)
resAT<-PCA(dataAt,graph=F)
plot(resAT)
resAT$eig
plot(resAT,selectMode="cos2 5")
plot(resAT,selectMod="cos2 5")
?plot.PCA
plot(resAT,selectMod="cos2 5",axes=c(1,2))
?plot.PCA
plot(resAT,select="cos2 5",axes=c(1,2))
plot(res2T,select="cos2 5",axes=c(1,2))
plot(res2T,select="cos2 5",axes=c(1,2))
ls()
plot(res2W,select="cos2 5",axes=c(1,2))
plot(res2T,select="cos2 5",axes=c(1,2))
plot(res2W,select="cos2 5",axes=c(1,2))
exit()
q9)
q()
